{{- define "matrix-stack.common.value-from-path" -}}
{{- $root := .root -}}
{{- with required "matrix-stack.common.value-from-path missing context" .context -}}
{{- $current := mustMergeOverwrite (dict) (mustDeepCopy $root.Values) -}}
{{- range (mustRegexSplit "\\." . -1) -}}
{{- if $current -}}
{{- $current = dig . nil $current -}}
{{- end -}}
{{- end -}}
{{ $current | toJson }}
{{- end -}}
{{- end -}}

{{- /*
There are several cases that need to be handled here:
* secret not provided in values.yaml
  * will be generated by the initSecrets job and mounted
  at /secrets/<release name>-<component name>-generated
  * should fail if initSecrets is not enabled
* secret reference provided in values.yaml
  * will be mounted at /secrets/<secret name>
* TODO: secret value provided in values.yaml
  * will be mounted at /secrets/<release fullname>-<component name>
* secret belongs to other component (ie. MAS shared secret for Synapse)
  * should always be mounted at /secrets/<secret-name>
  * this still needs to check if respective secret is provided or generated
    by init-secrets and act accordingly
*/ -}}
{{- define "matrix-stack.common.secret-path" -}}
{{- $root := .root -}}
{{- with required "matrix-stack.common.secret-path missing context" .context -}}
{{- $valuePath := required "matrix-stack.common.secret-path missing valuePath" .valuePath -}}
{{- $component := mustRegexSplit "\\." $valuePath -1 | first -}}
{{- $initSecretKey := required "matrix-stack.common.secret-path missing initSecretKey" .initSecretKey -}}
{{- $value := (include "matrix-stack.common.value-from-path" (dict "root" $root "context" $valuePath) | fromJson) -}}
{{- if $value -}}
{{- if $value.secretName -}}
{{ $value.secretName }}/{{ $value.secretKey }}
{{- else -}}
{{ include "matrix-stack.fullname" $root }}-{{ kebabcase $component }}/{{ $initSecretKey }}
{{- end -}}
{{- else -}}
{{- if $root.Values.initSecrets.enabled -}}
{{ include "matrix-stack.fullname" $root }}-{{ kebabcase $component }}-generated/{{ $initSecretKey }}
{{- else -}}
{{- fail (printf "initSecrets.enabled is false but no secret for %s provided" $valuePath) -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}

{{- define "matrix-stack.common.secret-volumes" -}}
{{- $root := .root -}}
{{- with required "matrix-stack.common.secret-volumes missing context" .context -}}
{{- $component := required "matrix-stack.common.secret-volumes missing component" .component -}}
{{- $usedSecrets := list -}}
{{- range (include (printf "matrix-stack.%s.secrets" $component) (dict "context" (get $root.Values ($component | camelcase | untitle)) "root" $root) | fromYamlArray) }}
{{- if not (has .secretName $usedSecrets) }}
- name: {{ .secretName }}
  secret:
    secretName: {{ .secretName }}
    defaultMode: 0400
{{- $usedSecrets = append $usedSecrets .secretName -}}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

{{- define "matrix-stack.common.secret-volumemounts" -}}
{{- $root := .root -}}
{{- with required "matrix-stack.common.secret-volumemounts missing context" .context -}}
{{- $component := required "matrix-stack.common.secret-volumemounts missing component" .component -}}
{{- $usedSecrets := list -}}
{{- range (include (printf "matrix-stack.%s.secrets" $component) (dict "context" (get $root.Values ($component | camelcase | untitle)) "root" $root) | fromYamlArray) }}
{{- if not (has .secretName $usedSecrets) }}
- name: {{ .secretName }}
  mountPath: /secrets/{{ .secretName }}
  defaultMode: 0400
{{- if .mountSubPath }}
  subPath: {{ .secretKey }}
{{- end }}
{{- $usedSecrets = append $usedSecrets .secretName -}}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
